/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.Controlador;
import ec.edu.ups.controlador.ControladorPersona;
import ec.edu.ups.controlador.ControladorTelefono;
import ec.edu.ups.modelo.Persona;
import ec.edu.ups.modelo.Telefono;
import javax.swing.JMenuItem;

/**
 *
 * @author NANCY
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private VentanaCrearUsuario ventanaCrearUsuario;
    private VentanaGestionTelefono ventanaGestionTelefono;
    private VentanaBuscar ventanaBuscar;
    private VentanaIniciarSecion ventanaIniciarSecion;
    
    private ControladorPersona controladorPersona;
    private ControladorTelefono controladorTelefono;
    
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        menuGestioTelefono.setVisible(false);
        menuCerrarSesion.setVisible(false);
        
        controladorPersona= new ControladorPersona();
        controladorTelefono = new ControladorTelefono();
        
        ventanaCrearUsuario= new VentanaCrearUsuario(controladorPersona);
        ventanaGestionTelefono= new VentanaGestionTelefono(controladorPersona,controladorTelefono);
        ventanaBuscar= new VentanaBuscar(controladorPersona,controladorTelefono);
        ventanaIniciarSecion= new VentanaIniciarSecion(controladorPersona, this, ventanaGestionTelefono); 
    }

    public JMenuItem getMenuBuscar() {
        return menuBuscar;
    }

    public JMenuItem getMenuCerrarSesion() {
        return menuCerrarSesion;
    }

    public JMenuItem getMenuCrearUsuario() {
        return menuCrearUsuario;
    }

    public JMenuItem getMenuGestioTelefono() {
        return menuGestioTelefono;
    }

    public JMenuItem getMenuIniciarSecion() {
        return menuIniciarSecion;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        menuCrearUsuario = new javax.swing.JMenuItem();
        menuIniciarSecion = new javax.swing.JMenuItem();
        menuGestioTelefono = new javax.swing.JMenuItem();
        menuCerrarSesion = new javax.swing.JMenuItem();
        menuBuscar = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        menuCrearUsuario.setMnemonic('o');
        menuCrearUsuario.setText("Crear Usuario");
        menuCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCrearUsuarioActionPerformed(evt);
            }
        });
        fileMenu.add(menuCrearUsuario);

        menuIniciarSecion.setText("Iniciar Secion");
        menuIniciarSecion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuIniciarSecionActionPerformed(evt);
            }
        });
        fileMenu.add(menuIniciarSecion);

        menuGestioTelefono.setMnemonic('s');
        menuGestioTelefono.setText("Gestios Telefono");
        menuGestioTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuGestioTelefonoActionPerformed(evt);
            }
        });
        fileMenu.add(menuGestioTelefono);

        menuCerrarSesion.setText("Cerrar Sesion");
        menuCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCerrarSesionActionPerformed(evt);
            }
        });
        fileMenu.add(menuCerrarSesion);

        menuBuscar.setMnemonic('a');
        menuBuscar.setText("Buscar");
        menuBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBuscarActionPerformed(evt);
            }
        });
        fileMenu.add(menuBuscar);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void menuGestioTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGestioTelefonoActionPerformed
        ventanaGestionTelefono.setVisible(true);
        desktopPane.add(ventanaGestionTelefono);
    }//GEN-LAST:event_menuGestioTelefonoActionPerformed

    private void menuBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBuscarActionPerformed
        desktopPane.add(ventanaBuscar);
        ventanaBuscar.setVisible(true);
        
    }//GEN-LAST:event_menuBuscarActionPerformed

    private void menuCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCrearUsuarioActionPerformed
        desktopPane.add(ventanaCrearUsuario);
        ventanaCrearUsuario.setVisible(true);
        
    }//GEN-LAST:event_menuCrearUsuarioActionPerformed

    private void menuIniciarSecionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuIniciarSecionActionPerformed
        desktopPane.add(ventanaIniciarSecion);
        ventanaIniciarSecion.setVisible(true);
        
    }//GEN-LAST:event_menuIniciarSecionActionPerformed

    private void menuCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCerrarSesionActionPerformed
        menuCrearUsuario.setVisible(true);
        menuBuscar.setVisible(true);
        menuIniciarSecion.setVisible(true);
        menuGestioTelefono.setVisible(false);
        menuCerrarSesion.setVisible(false);
    }//GEN-LAST:event_menuCerrarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuBuscar;
    private javax.swing.JMenuItem menuCerrarSesion;
    private javax.swing.JMenuItem menuCrearUsuario;
    private javax.swing.JMenuItem menuGestioTelefono;
    private javax.swing.JMenuItem menuIniciarSecion;
    // End of variables declaration//GEN-END:variables

}
