/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;


import ec.edu.ups.controlador.ControladorPersona;
import ec.edu.ups.modelo.Persona;
import javax.swing.JOptionPane;

/**
 *
 * @author NANCY
 */
public class VentanaIniciarSecion extends javax.swing.JInternalFrame {

    private ControladorPersona controladorPersona;
    private VentanaPrincipal ventanaPrincipal;
    private VentanaGestionTelefono ventanaGestionTelefono;
    //private VentanaGestionUsuario ventanaGestionUsuario;
    /**
     * Creates new form VentanaIniciarSecion
     * @param controladorPersona
     * @param ventanaPrincipal
     * @param ventanaGestionTelefono
     */
    public VentanaIniciarSecion(ControladorPersona controladorPersona, VentanaPrincipal ventanaPrincipal,VentanaGestionTelefono ventanaGestionTelefono) {
        initComponents();
        
        this.controladorPersona = controladorPersona;
        this.ventanaPrincipal = ventanaPrincipal;
        this.ventanaGestionTelefono = ventanaGestionTelefono;
        //this.ventanaGestionUsuario = ventanaGestionUsuario;
    }
    public void limpiar() {
        txtCorreo.setText("");
        txtContra.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        txtContra = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();

        setClosable(true);

        jLabel1.setText("Correo");

        jLabel2.setText("Contraseña");

        btnLogin.setBackground(new java.awt.Color(0, 0, 0));
        btnLogin.setForeground(new java.awt.Color(255, 255, 0));
        btnLogin.setText("Iniciar Secion");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCorreo)
                    .addComponent(txtContra, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(btnLogin)
                .addContainerGap(153, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(btnLogin)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        Persona persona = controladorPersona.iniciarSesion(txtCorreo.getText(), txtContra.getText());
 
        if (persona != null) {
            ventanaPrincipal.getMenuGestioTelefono().setVisible(true);
            ventanaPrincipal.getMenuCerrarSesion().setVisible(true);
            ventanaPrincipal.getMenuIniciarSecion().setVisible(false);
            ventanaPrincipal.getMenuCrearUsuario().setVisible(false);
            ventanaPrincipal.getMenuBuscar().setVisible(false);
            JOptionPane.showMessageDialog(this, "Bienvenido"+"  "+persona.getNombre());
            ventanaGestionTelefono.setUsuario(persona);
            //ventanaGestionUsuario.setUsuario(persona);
            limpiar();
            dispose();
        } else {
            
            JOptionPane.showMessageDialog(this, "Usuario no encontrado");
        }
    }//GEN-LAST:event_btnLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtContra;
    private javax.swing.JTextField txtCorreo;
    // End of variables declaration//GEN-END:variables
}
